# Generated by Django 5.0 on 2024-01-12 07:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cart_delete_customerprofile'),
        ('seller', '0005_alter_product_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=25, unique=True)),
                ('order_no', models.CharField(max_length=40)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('payment_id', models.CharField(max_length=25, null=True, unique=True)),
                ('signature_id', models.CharField(max_length=25, null=True, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'order_tb',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='order placed', max_length=100)),
                ('packed_date', models.DateField(default=datetime.date.today, null=True)),
                ('cancelled_date', models.DateField(default=datetime.date.today, null=True)),
                ('cancellation_reason', models.CharField(max_length=100)),
                ('delivery_out', models.DateField(default=datetime.date.today, null=True)),
                ('delivered_date', models.DateField(default=datetime.date.today, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
            options={
                'db_table': 'orderItem_tb',
            },
        ),
    ]
