# Generated by Django 5.0 on 2024-02-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_productquestion_answers_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Review_Pic/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.productreview')),
            ],
            options={
                'db_table': 'reviewPic_tb',
            },
        ),
    ]
