# Generated by Django 5.0 on 2024-01-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('company_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('profile_image', models.ImageField(upload_to='seller/')),
                ('login_id', models.IntegerField(null=True)),
                ('account_name', models.BigIntegerField()),
                ('bank_name', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
            options={
                'db_table': 'seller_tb',
            },
        ),
    ]
