# Generated by Django 5.0 on 2024-01-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='account_name',
        ),
        migrations.AddField(
            model_name='seller',
            name='account_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_branch',
            field=models.CharField(default='', max_length=20),
        ),
    ]
